# netlify.toml

# This section tells Netlify how to build your React frontend
[build]
  base    = "client"
  command = "npm install && npm run build"
  publish = "dist" # Correct path

# This section tells Netlify where your serverless functions are
[functions]
  directory = "netlify/functions"

# This rule proxies API requests to your serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200